"""add product material/process/dimension fields

Revision ID: 2bf5b33e2492
Revises: 28d007bc0f21
Create Date: 2026-07-11 14:17:28.418432
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf5b33e2492'
down_revision: Union[str, None] = '28d007bc0f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('material_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('process_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('length', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('width', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('height', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('area', sa.Numeric(precision=14, scale=3), nullable=True))
    op.add_column('products', sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True))
    op.create_foreign_key(None, 'products', 'processes', ['process_id'], ['id'])
    op.create_foreign_key(None, 'products', 'materials', ['material_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'quantity')
    op.drop_column('products', 'area')
    op.drop_column('products', 'height')
    op.drop_column('products', 'width')
    op.drop_column('products', 'length')
    op.drop_column('products', 'process_id')
    op.drop_column('products', 'material_id')
    # ### end Alembic commands ###
