"""drop product dimension fields

Revision ID: 59e98f307244
Revises: 2bf5b33e2492
Create Date: 2026-07-11 15:28:17.551353
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e98f307244'
down_revision: Union[str, None] = '2bf5b33e2492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_process_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_material_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'width')
    op.drop_column('products', 'material_id')
    op.drop_column('products', 'process_id')
    op.drop_column('products', 'quantity')
    op.drop_column('products', 'length')
    op.drop_column('products', 'area')
    op.drop_column('products', 'height')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('height', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('area', sa.NUMERIC(precision=14, scale=3), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('length', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('quantity', sa.NUMERIC(precision=14, scale=3), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('process_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('width', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('products_material_id_fkey'), 'products', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(op.f('products_process_id_fkey'), 'products', 'processes', ['process_id'], ['id'])
    # ### end Alembic commands ###
