"""add_payee_company_name_to_outsource_payments

Revision ID: ad64d94c02a5
Revises: ef45f9b8eae8
Create Date: 2026-07-09 15:34:11.165328
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad64d94c02a5'
down_revision: Union[str, None] = 'ef45f9b8eae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outsource_payments', sa.Column('payee_company_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outsource_payments', 'payee_company_name')
    # ### end Alembic commands ###
