"""fix operation_log model

Revision ID: bd80b5a9576a
Revises: 666e093af5d2
Create Date: 2026-06-29 17:02:44.326659
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd80b5a9576a'
down_revision: Union[str, None] = '666e093af5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_logs', sa.Column('user_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_logs', 'user_name')
    # ### end Alembic commands ###
