"""add_quote_item_unit_and_use_area

Revision ID: c1d2e3f4a5b6
Revises: bd80b5a9576a
Create Date: 2026-07-03

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d2e3f4a5b6'
down_revision: Union[str, None] = 'a32c1ade8b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_items', sa.Column('length_unit', sa.String(16), nullable=True, server_default='m'))
    op.add_column('quote_items', sa.Column('width_unit', sa.String(16), nullable=True, server_default='m'))
    op.add_column('quote_items', sa.Column('height_unit', sa.String(16), nullable=True, server_default='m'))
    op.add_column('quote_items', sa.Column('use_area', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_items', 'use_area')
    op.drop_column('quote_items', 'height_unit')
    op.drop_column('quote_items', 'width_unit')
    op.drop_column('quote_items', 'length_unit')
    # ### end Alembic commands ###
