"""add contract models

Revision ID: c3030d853060
Revises: cc23a92b0294
Create Date: 2026-07-10 22:03:29.692009
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3030d853060'
down_revision: Union[str, None] = 'cc23a92b0294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_no', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unpaid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sign_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('our_signatory', sa.String(length=128), nullable=True, comment='我方签约人'),
    sa.Column('customer_signatory', sa.String(length=128), nullable=True, comment='客户签约人'),
    sa.Column('contract_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=True, comment='合同条款内容'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no')
    )
    op.create_table('contract_quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('outsource_tasks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('project_costs', 'group_name',
               existing_type=sa.VARCHAR(length=255),
               comment='分项名（1级分组）',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('project_costs', 'quantity',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='数量',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('project_costs', 'unit',
               existing_type=sa.VARCHAR(length=32),
               comment='单位',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('project_costs', 'unit_price',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='单价',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.drop_constraint(op.f('fk_project_costs_order_item_id'), 'project_costs', type_='foreignkey')
    op.create_foreign_key(None, 'project_costs', 'order_items', ['order_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_costs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_project_costs_order_item_id'), 'project_costs', 'order_items', ['order_item_id'], ['id'])
    op.alter_column('project_costs', 'unit_price',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment=None,
               existing_comment='单价',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('project_costs', 'unit',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='单位',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('project_costs', 'quantity',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment=None,
               existing_comment='数量',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('project_costs', 'group_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='分项名（1级分组）',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_column('outsource_tasks', 'deleted_at')
    op.drop_table('contract_orders')
    op.drop_table('contract_quotes')
    op.drop_table('contracts')
    # ### end Alembic commands ###
