"""add_paid_amount_to_outsource_tasks

Revision ID: ef45f9b8eae8
Revises: 6d88d54999c7
Create Date: 2026-07-09 15:11:26.614705
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef45f9b8eae8'
down_revision: Union[str, None] = '6d88d54999c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('acceptance_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('acceptance_attachments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('acceptance_forms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('acceptance_forms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('acceptance_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('acceptance_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_owner_id'), table_name='conversations')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_column('notifications', 'deleted_at')
    # Add columns as nullable first to handle existing rows
    op.add_column('outsource_tasks', sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('outsource_tasks', sa.Column('unpaid_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    # Set default values for existing rows
    op.execute("UPDATE outsource_tasks SET paid_amount = 0 WHERE paid_amount IS NULL")
    op.execute("UPDATE outsource_tasks SET unpaid_amount = total_amount WHERE unpaid_amount IS NULL")
    # Now set nullable=False
    op.alter_column('outsource_tasks', 'paid_amount', nullable=False)
    op.alter_column('outsource_tasks', 'unpaid_amount', nullable=False)
    op.alter_column('project_costs', 'payment_method',
               existing_type=sa.VARCHAR(length=32),
               comment='付款方式：现金支付/微信支付/转账支付/对公支付/其它支付',
               existing_comment='付款方式',
               existing_nullable=True)
    op.alter_column('quotes', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'token_version',
               existing_type=sa.INTEGER(),
               comment='JWT token 版本号',
               existing_comment='JWT token 版本号，用于强制重新登录',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token_version',
               existing_type=sa.INTEGER(),
               comment='JWT token 版本号，用于强制重新登录',
               existing_comment='JWT token 版本号',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('quotes', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('project_costs', 'payment_method',
               existing_type=sa.VARCHAR(length=32),
               comment='付款方式',
               existing_comment='付款方式：现金支付/微信支付/转账支付/对公支付/其它支付',
               existing_nullable=True)
    op.drop_column('outsource_tasks', 'unpaid_amount')
    op.drop_column('outsource_tasks', 'paid_amount')
    op.add_column('notifications', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_owner_id'), 'conversations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.alter_column('acceptance_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('acceptance_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('acceptance_forms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('acceptance_forms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('acceptance_attachments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('acceptance_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
