import type { PageCapabilityMap } from './types'

export const salesDeliveryCapabilities: PageCapabilityMap = {
  dashboard: {
    title: '驾驶舱',
    purpose: '汇总今日任务、订单进度、经营数据和待处理事项',
    workflowStage: 'overview',
    availableActions: ['查看今日任务', '查看待处理订单', '查看经营概况'],
    quickActions: [
      { label: '今日任务', prompt: '查询今日的设计、制作和安装任务' },
      { label: '待处理订单', prompt: '查看有哪些未完成的订单' },
    ],
  },
  customer_list: {
    title: '客户列表',
    purpose: '查询和维护客户档案，进入客户详情查看业务往来',
    workflowStage: 'customer',
    availableActions: ['搜索客户', '新建客户', '查看客户详情'],
    quickActions: [
      { label: '搜索客户', prompt: '帮我搜索客户' },
      { label: '欠款客户', prompt: '查看客户的欠款情况' },
    ],
  },
  customer_detail: {
    title: '客户详情',
    purpose: '查看客户档案、联系人、历史订单和应收情况',
    workflowStage: 'customer',
    availableActions: ['查看客户资料', '查看历史订单', '查看客户欠款', '创建报价'],
    quickActions: [
      { label: '欠款', prompt: '这个客户欠多少钱' },
      { label: '订单', prompt: '这个客户有哪些订单' },
    ],
  },
  order_list: {
    title: '订单列表',
    purpose: '查询订单并跟踪从确认到交付完成的整体状态',
    workflowStage: 'order',
    availableActions: ['搜索订单', '筛选未完成订单', '查看订单详情'],
  },
  order_recycle: {
    title: '订单回收站',
    purpose: '查看已删除订单并按权限恢复',
    workflowStage: 'order',
    availableActions: ['查看已删除订单', '恢复订单'],
  },
  order_detail: {
    title: '订单详情',
    purpose: '查看订单信息、交付任务、验收与收款进度',
    workflowStage: 'order_delivery',
    availableActions: ['查看订单进度', '查看关联任务', '查看收款情况'],
    quickActions: [
      { label: '进度', prompt: '这个订单做到哪了' },
      { label: '任务', prompt: '这个订单有哪些任务' },
      { label: '收款', prompt: '这个订单的收款情况' },
    ],
  },
  quote_list: {
    title: '报价列表',
    purpose: '维护常规报价单并跟踪确认和转订单状态',
    workflowStage: 'quote',
    availableActions: ['搜索报价', '新建报价', '查看报价详情'],
  },
  quote_create: {
    title: '新建报价',
    purpose: '为客户录入项目明细并生成常规报价草稿',
    workflowStage: 'quote',
    availableActions: ['选择客户', '添加报价项目', '保存报价草稿'],
  },
  quote_edit: {
    title: '编辑报价',
    purpose: '修改未锁定报价单的项目、数量和价格',
    workflowStage: 'quote',
    availableActions: ['修改报价项目', '重新计算金额', '保存报价'],
  },
  cdr_quote_list: {
    title: '智能报价列表',
    purpose: '管理由设计文件解析生成的智能报价单',
    workflowStage: 'quote',
    availableActions: ['搜索智能报价', '新建智能报价', '查看报价详情'],
    quickActions: [{ label: '智能报价', prompt: '帮我生成智能报价草稿' }],
  },
  cdr_quote_create: {
    title: '新建智能报价',
    purpose: '导入设计内容并生成可复核的智能报价',
    workflowStage: 'quote',
    availableActions: ['导入设计内容', '生成报价明细', '保存报价草稿'],
  },
  cdr_quote_detail: {
    title: '智能报价详情',
    purpose: '查看智能报价版本、明细、审批记录并转为订单',
    workflowStage: 'quote',
    availableActions: ['查看报价内容', '提交审批', '转为订单'],
    quickActions: [
      { label: '报价内容', prompt: '这个报价是什么内容' },
      { label: '转为订单', prompt: '生成这个报价的订单' },
    ],
  },
  cdr_quote_edit: {
    title: '编辑智能报价',
    purpose: '调整智能报价项目、工艺、价格和版本信息',
    workflowStage: 'quote',
    availableActions: ['编辑报价明细', '计算报价', '保存新版本'],
  },
  price_rules: {
    title: '定价规则',
    purpose: '维护智能报价使用的材料、工艺和计价规则',
    workflowStage: 'pricing',
    availableActions: ['查询定价规则', '新增规则', '调整规则'],
  },
  contract_list: {
    title: '合同列表',
    purpose: '查询和维护订单相关的常规合同',
    workflowStage: 'contract',
    availableActions: ['搜索合同', '新建合同', '查看合同'],
  },

  contract_detail: {
    title: '合同详情',
    purpose: '查看合同条款、管理子项目和关联订单',
    workflowStage: 'contract',
    availableActions: ['查看合同', '添加项目', '编辑合同'],
  },
  acceptance_list: {
    title: '验收列表',
    purpose: '管理安装完成后的验收单和待验收项目',
    workflowStage: 'acceptance',
    availableActions: ['查询验收单', '创建验收单', '查看验收详情'],
  },
  acceptance_detail: {
    title: '验收详情',
    purpose: '核对验收项目、记录客户意见并完成或驳回验收',
    workflowStage: 'acceptance',
    availableActions: ['检查验收项目', '提交验收', '驳回返工'],
  },
  design_task_list: {
    title: '设计任务列表',
    purpose: '查询、分配和跟踪设计任务',
    workflowStage: 'design',
    availableActions: ['查看设计任务', '筛选待处理任务', '创建设计任务'],
    quickActions: [{ label: '今日设计', prompt: '查询今天的设计任务' }],
  },
  design_task_detail: {
    title: '设计任务详情',
    purpose: '查看设计要求、设计稿、客户反馈和确认状态',
    workflowStage: 'design',
    availableActions: ['查看设计要求', '更新设计进度', '提交客户确认'],
  },
  production_task_list: {
    title: '制作任务列表',
    purpose: '查询、排产和跟踪制作任务',
    workflowStage: 'production',
    availableActions: ['查看制作任务', '筛选待制作任务', '安排制作'],
    quickActions: [{ label: '今日制作', prompt: '查询今天的制作任务' }],
  },
  production_task_board: {
    title: '项目看板',
    purpose: '按状态直观查看制作任务并进行排产调度',
    workflowStage: 'production',
    availableActions: ['查看排产状态', '调整任务状态', '查看任务详情'],
  },
  production_task_detail: {
    title: '制作任务详情',
    purpose: '查看材料工艺、制作进度、质检和返工信息',
    workflowStage: 'production',
    availableActions: ['查看制作要求', '更新制作进度', '提交质检'],
  },
  installation_task_list: {
    title: '安装任务列表',
    purpose: '查询、派工和跟踪现场安装任务',
    workflowStage: 'installation',
    availableActions: ['查看安装任务', '安排安装', '筛选待安装任务'],
    quickActions: [
      { label: '今日安装', prompt: '查询今天的安装任务' },
      { label: '安排安装', prompt: '帮我安排明天安装' },
    ],
  },
  installation_task_detail: {
    title: '安装任务详情',
    purpose: '查看安装地址、人员、时间、现场照片和完成状态',
    workflowStage: 'installation',
    availableActions: ['查看安装要求', '更新安装进度', '提交待验收'],
  },
  product_manage: {
    title: '产品/材质/工艺',
    purpose: '维护报价统一使用的产品、材质、工艺组合及默认计价信息',
    workflowStage: 'master_data',
    availableActions: ['查询产品/材质/工艺', '新增产品/材质/工艺组合', '调整产品/材质/工艺组合'],
  },
  outsource_vendors: {
    title: '外协商列表',
    purpose: '维护外协供应商档案和合作信息',
    workflowStage: 'outsource',
    availableActions: ['查询外协商', '新增外协商', '查看合作记录'],
  },
  outsource_tasks: {
    title: '外协任务列表',
    purpose: '管理委外制作任务、交期、金额和回货状态',
    workflowStage: 'outsource',
    availableActions: ['查询外协任务', '创建外协任务', '更新任务进度'],
  },
  outsource_task_recycle: {
    title: '外协任务回收站',
    purpose: '查看已删除外协任务并按权限恢复',
    workflowStage: 'outsource',
    availableActions: ['查看已删除任务', '恢复外协任务'],
  },
  inventory: {
    title: '库存管理',
    purpose: '查询材料库存并登记入库、出库和盘点',
    workflowStage: 'inventory',
    availableActions: ['查询库存', '登记入库', '登记出库', '库存盘点'],
  },
}
